language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  # Install Drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  # Install apache
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)/www?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - "mysql -e 'create database drupal;'"
  - phpenv rehash
  - bash scripts/setup
  - bash scripts/build

  # Download and install Apache solr
  - wget http://wiki.gizra-labs.com/images/e/ee/Apache-solr-3.6.2.zip
  - unzip -o Apache-solr-3.6.2.zip
  - cd apache-solr-3.6.2/example/solr/conf
  # Copy the solr config files from the apache solr module
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/modules/contrib/apachesolr/solr-conf/solr-3.x/* .
  # Copy the modified solrconfig.xml file to commit records every 20 seconds so items will show up in search sooner
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/behat/solr/solrconfig.xml .
  - cd ../../
  - java -jar start.jar &
  - sleep 10
  - cd /home/travis/build/openscholar/openscholar

  # Install a multi-tanent, development site.
  - cd www
  - mkdir -p /tmp
  - mkdir -p /tmp/devel-mails
  - mkdir -p sites/default/files
  - sudo chmod 777 /tmp -R
  - sudo chmod 777 sites/default -R
  - time drush si openscholar --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal openscholar_flavor_form.os_profile_flavor=development openscholar_install_type.os_profile_type=vsite --yes
  - drush vset purl_base_domain http://127.0.0.1
  - drush en os_migrate_demo -y
  - drush mi --all --user=1

  # Index site using Apache solr
  - drush en os_search_solr -y
  - drush solr-mark-all
  - drush solr-index

  # Copy Behat configuration file.
  - cd profiles/openscholar/behat
  - cp behat.local.yml.travis behat.local.yml
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source
  - sudo cat /var/log/apache2/error.log

script:
  - ./bin/behat --tags=~wip

after_script:
    - sudo cat /var/log/apache2/error.log
