language: php
sudo: false

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

addons:
 apt:
  packages:
    - php5-cgi
    - php5-mysql
    - php5-curl

cache:
  apt: true
  directories:
    - openscholar/solr-script
    - openscholar/modules/contrib
    - openscholar/themes/contrib
    - openscholar/libraries

env:
  global:
    - secure: "kbYKhyQY0mHBRcMz82PQDkWSrAjGeQVyk/VC5TJkcGd06QW6ovK3Xyy1FvoyID8ktG56EAe2IOnSE3kt51h8mqGlR6SVfluBJobgWjgcY3+6kSWPNsVrZNUL+hwHytM+OhbacUXP/PedXP55DMMPP0GVQlPgdzaUjzzlScj3w3A="
    - "ARTIFACTS_S3_BUCKET=travisos"
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - secure: "J+GWGGesskpTxCNq/YJJaL+DRnNeFbF3vslBPd47OKQI5kaH5SHfVH70iBaB3taBadf9XuJOj/NdHTSwjSpcY17TROw7ajG0KAOySsgDdpeAQ6lNmPdTc3TPicB6dfv6weGPzJB/pGVZW/ZirOodJsInbUnY7y9KsxfePGUKn4A="
    - secure: "HvsIfxg/7BaZepgsKc7s9LK/TEf75drUm+LlyE1BiO3HTq5wwOuyWYiJ5/40JhAGnGsU7dEoUqTR5JePjyQxlV6uyIc6suOsZJz4fOuukEPs/dG9B5W4eMP4cS2UoIb/QU2YEd6Uk0OZWCdZCsHlT1j1MFUiuRHWYSIcvrDFKkY="
  matrix:
#    - TEST_SUITE=restful #- working
#    - TEST_SUITE=features_first #- working
#    - TEST_SUITE=features_second #- working with wip
#    - TEST_SUITE=harvard #- working

#    - TEST_SUITE=misc_first
#    - TEST_SUITE=misc_second
#    - TEST_SUITE=solr # - working
#    - TEST_SUITE=taxonomy # - working
    - TEST_SUITE=vsite
#    - TEST_SUITE=widgets
#    - TEST_SUITE=media_browser

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:7.*@dev
  - rvm 1.9.3 do gem install net-ssh -v 2.9.2
  - rvm 1.9.3 do gem install mime-types -v 2.6.2
  - "gem install travis-artifacts"

  # Install bower
  - npm install -g bower

  # Set up the lincoln virtual domain.
#  -  sh -c "echo 127.0.1.1	lincoln.local >> /etc/hosts"
#  -  sh -c "cat openscholar/behat/lincoln-vhost.txt > /etc/apache2/sites-available/lincoln"
#  -  a2ensite lincoln
  - phpenv rehash
  - bash scripts/setup
  - bash scripts/build cached

  # Install a multi-tanent, development site.
  - cd www
  - time drush si openscholar --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal openscholar_flavor_form.os_profile_flavor=development openscholar_install_type.os_profile_type=vsite --yes
  - drush vset purl_base_domain http://127.0.0.1:8888

  # Migrate, enable harvard courses and index data.
  - drush en os_migrate_demo -y
  - drush mi --all --user=1

  - bash profiles/openscholar/behat/install_modules.sh

  # Fire up the server.
  - cp profiles/openscholar/behat/router.php router.php
  - drush rs 8888 router.php > ~/rs.log 2>&1 &

  # Copy Behat configuration file.
  - cd profiles/openscholar/behat
  - cp behat.local.yml.travis behat.local.yml
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source

  # Other
  - drush vset oembedembedly_api_key $EMBEDLYAPIKEY

script:

  # Run the assets backend.
  - cd node_backend
  - npm install
  - nohup bash -c "node index.js 2>&1 &"
  - cd -

  # Start running the tests.
  - ./bin/behat --tags=$TEST_SUITE

after_failure: # this will of course run only on failure
  - "travis-artifacts upload --path /tmp/screenshots"
  - cat ~/rs.log
