language: php
sudo: false

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

addons:
  apt:
    sources:
      - apt-get update
      - apt-get install apache2
      - apt-get update
      - apt-get install build-essential chrpath libssl-dev libxft-dev
      - apt-get install libfreetype6 libfreetype6-dev
      - apt-get install libfontconfig1 libfontconfig1-dev

env:
  - TEST_SUITE=features_first
#  - TEST_SUITE=features_second
#  - TEST_SUITE=harvard
##  - TEST_SUITE=javscript
#  - TEST_SUITE=misc_first
#  - TEST_SUITE=misc_second
#  - TEST_SUITE=solr
#  - TEST_SUITE=taxonomy
#  - TEST_SUITE=vsite
#  - TEST_SUITE=widgets

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev

  # Install apache
  - a2enmod actions
  - a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/74f4fec92c064c4f683fef28a6098caf0f038de7/gistfile1.txt)" | tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/8066fda124b6c86f69ad32a010b8c22bbaf868e8/gistfile1.txt)" | sed -e "s,PATH,`pwd`/www,g" | tee /etc/apache2/sites-available/default > /dev/null

 # Install phantom JS.
  - export PHANTOM_JS="phantomjs-1.9.7-linux-x86_64"
  - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  - mv $PHANTOM_JS.tar.bz2 /usr/local/share/
  - tar xvjf /usr/local/share/$PHANTOM_JS.tar.bz2
  - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/share/phantomjs
  - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
  - ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/bin/phantomjs

  # Set up the lincoln virtual domain.
  - service apache2 restart
  - sh -c "echo 127.0.1.1	lincoln.local >> /etc/hosts"
  - sh -c "cat openscholar/behat/lincoln-vhost.txt > /etc/apache2/sites-available/lincoln"
  - a2ensite lincoln
  - service apache2 reload
  - "mysql -e 'create database drupal;'"
  - phpenv rehash
  - bash scripts/setup
  - bash scripts/build

  # Configure MySQL.
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - echo -e "[server]\nmax_allowed_packet=64M" | tee -a /etc/mysql/conf.d/drupal.cnf
  - service mysql reload
  - mysql -e "SET GLOBAL wait_timeout=300;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"

  # Download and install Apache solr
  - wget https://archive.apache.org/dist/lucene/solr/3.6.2/apache-solr-3.6.2.zip
  - unzip -o apache-solr-3.6.2.zip
  - cd apache-solr-3.6.2/example/solr/conf

  # Copy the solr config files from the apache solr module
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/modules/contrib/apachesolr/solr-conf/solr-3.x/* .

  # Copy the modified solrconfig.xml file to commit records every 20 seconds so items will show up in search sooner
  - yes | cp /home/travis/build/openscholar/openscholar/www/profiles/openscholar/behat/solr/solrconfig.xml .
  - cd ../../
  - java -jar start.jar &
  - sleep 10
  - cd /home/travis/build/openscholar/openscholar

  # Install a multi-tanent, development site.
  - cd www
  - mkdir -p /tmp
  - mkdir -p /tmp/devel-mails
  - mkdir -p sites/default/files
  - chmod 777 /tmp -R
  - chmod 777 sites/default -R
  - time drush si openscholar --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal openscholar_flavor_form.os_profile_flavor=development openscholar_install_type.os_profile_type=vsite --yes
  - drush vset purl_base_domain http://127.0.0.1

  # Migrate, enable harvard courses and index data.
  - drush en os_migrate_demo -y
  - drush mi --all --user=1
  - drush en harvard_courses -y
  - drush cc all
  - drush search-index

  # Index site using Apache solr
  - drush en os_search_solr -y
  - drush solr-mark-all
  - drush solr-index

  # Trying to execute the internal solr commit
  - sleep 10
  - wget http://localhost:8983/solr/update?commit=true

  # Copy Behat configuration file.
  - cd profiles/openscholar/behat
  - cp behat.local.yml.travis behat.local.yml
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-source
  - cat /var/log/apache2/error.log

script:

  # Run selenium.
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - wget http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar
  - java -jar selenium-server-standalone-2.40.0.jar -p 4444 &
  - sleep 5

  # Run phantomJs.
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  - ./bin/behat --tags=$TEST_SUITE

after_script:
  - cat /var/log/apache2/error.log
